### PR TITLE
Add support for overriding home page on Firefox

### LINKED ISSUE #48: Firefox 57 shows standard Firefox new tab page upon startup instead of the humble one
When Firefox 57 first starts up with the default settings, it shows the new tab page. But even with this extension installed, it does not show the custom one this extension provides, it shows the standard Firefox one. I'm using the Solus operating system if that makes any difference.

### PR DESCRIPTION
**Pull request by bravechamp**
Fixes #48 and #68

### CODE REVIEW

**Comment by quodroc** [comment]
I wish there was a way to make this optional. Some people might want a different homepage.

**Comment by bravechamp** [comment]
The setting is already available in Firefox settings page (about:preferences). User can choose to use new tab page provided by HNTP or use a custom page.

**Comment by TCB13** [comment]
> The setting is already available in Firefox settings page (about:preferences). User can choose to use new tab page provided by HNTP or use a custom page.

How so, it doesn't work:

Annotation 2020-02-17 214959

**Comment by bravechamp** [comment]
image
Are you sure you installed the addon with my PR? Just tested on Firefox 73 (Arch Linux)

**Comment by TCB13** [comment]
>  Are you sure you installed the addon with my PR? Just tested on Firefox 73 (Arch Linux)

Okay, that one works just fine. :)

**Comment by TCB13** [comment]
Please merge this!

**Comment by quodroc** [comment]
I don't want to force this on users who may want a different homepage and unfortunately there's no way to make it optional.

However, since 1285aad in version 1.24.1 I believe the extension URL does not change anymore so you should be able to set it as homepage as follows:

1. Open preferences in new window.
2. Open new (humble) tab in same window.
3. In preferences, under homepage, click on "Use Current Pages".

**Comment by TCB13** [comment]
@quodroc that seems to works, lets see if if the URL doesn't change.

**Comment by bravechamp** [comment]
image

It's possible to change it on Firefox now.

**Comment by ibillingsley** [comment]
Added in version 1.26
(I made the change myself instead of merging this PR since there was a conflict)

**Pull request closed without merging**
